=== DnyaneshRP/SPPU-Practicals/WTL - Web Technology Laboratory/WTL4/employee.dtd
<!ELEMENT company (employee+)>
<!ELEMENT employee (id, name, designation, salary)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT designation (#PCDATA)>
<!ELEMENT salary (#PCDATA)>

=== DnyaneshRP/SPPU-Practicals/WTL - Web Technology Laboratory/WTL4/employee1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!DOCTYPE company SYSTEM "employee.dtd">

<company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:noNamespaceSchemaLocation="employee.xsd">
    <employee class="header">
        <id>ID</id>
        <name>Employee Name</name>
        <designation>Role</designation>
        <salary>Salary</salary>
    </employee>
    <employee>
        <id>101</id>
        <name>John Doe</name>
        <designation>Software Engineer</designation>
        <salary>75000</salary>
    </employee>
    <employee>
        <id>102</id>
        <name>Jane Smith</name>
        <designation>Project Manager</designation>
        <salary>90000</salary>
    </employee>
    <employee>
        <id>103</id>
        <name>Michael Johnson</name>
        <designation>Software Engineer</designation>
        <salary>85000</salary>
    </employee>
</company>

=== DnyaneshRP/SPPU-Practicals/WTL - Web Technology Laboratory/WTL4/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="style.xsl"?>

<!DOCTYPE company SYSTEM "employee.dtd">

<company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:noNamespaceSchemaLocation="employee.xsd">
    <employee>
        <id>101</id>
        <name>John Doe</name>
        <designation>Software Engineer</designation>
        <salary>75000</salary>
    </employee>
    <employee>
        <id>102</id>
        <name>Jane Smith</name>
        <designation>Project Manager</designation>
        <salary>90000</salary>
    </employee>
    <employee>
        <id>103</id>
        <name>Michael Johnson</name>
        <designation>Software Engineer</designation>
        <salary>85000</salary>
    </employee>
</company>
